# Site settings
title: "Ömer Ayyıldız's Resume"
description: "Ömer Ayyıldız Online Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ömer Ayyıldız"
resume_title:                   "Experience Designer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "me@omerayyildiz.com"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-555"
resume_contact_address:         "İstanbul / Türkiye"

resume_header_contact_info:     "me@omerayyildiz.com"
display_header_contact_info:    "true"

resume_header_intro: >-
  <p>I began my design journey <b>in high school</b> and transitioned from programming to product design in 2020, specializing in user experiences and graphic design. Alongside my university education, I gained real-world experience by working as a freelance designer for various design studios and companies both domestically and internationally.</p>
  <p>I am a professional <b>focused on solving problems and developing user-centered designs</b>. My knowledge in <b>user research, information architecture, interaction design, and programming</b> brings a unique perspective and added value to my projects.</p>
  <p>My goal is to follow in the footsteps of my esteemed mentors and design what is <b>"right" for people and society.</b></p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_linkedin_url:          "https://www.linkedin.com/in/omerayyildizwork"
  resume_website_url:           "https://omerayyildiz.com"
  resume_pdf_url:               "https://drive.google.com/file/d/1_o1tUrymdxxp8Iu32xfh1N41V6vycA48/view?usp=sharing"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
