# Site settings
title: "Ömer Ayyıldız's Resume"
description: "Ömer Ayyıldız Online Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ömer Ayyıldız"
resume_title:                   "Experience Designer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "me@omerayyildiz.com"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-555"
resume_contact_address:         "İstanbul / Türkiye"

resume_header_contact_info:     "me@omerayyildiz.com"
display_header_contact_info:    "true"

resume_header_intro: >-
  <p>I began my journey of thinking creatively and designing <b>during my high school years.</b> Initially <b>starting with programming,</b> my path evolved into graphic and product design while pursuing a degree in <b>Fine Arts at university</b>. What began as a production process within school groups expanded into collaborations with volunteer communities, non-profits, startups, and corporate organizations.</p>
  <p>I'm a professional dedicated to delivering <b>user-centered solutions and crafting inspiring stories.</b> With expertise in <b>user research, information architecture, experience design, branding, and programming,</b> I bring a unique perspective to every project, always focusing on creating <b>meaningful</b>, human-centered experiences.</p>
  <p>My goal is to follow in the footsteps of my esteemed mentors and design what is <b>"right" for people and society.</b></p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_linkedin_url:          "https://www.linkedin.com/in/omerayyildizwork"
  resume_website_url:           "https://omerayyildiz.com"
  resume_pdf_url:               "https://drive.google.com/file/d/1Ymbn3-gxAV76PbH1-NcoNSb3d7AGcT4W/view?usp=share_link"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
