# Site settings
title: "Ömer Ayyıldız's Resume"
description: "Ömer Ayyıldız Online Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ömer Ayyıldız"
resume_title:                   "Graphic Designer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "me@omerayyildiz.com"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-555"
resume_contact_address:         "Istanbul / Turkey"

resume_header_contact_info:     "me@omerayyildiz.com"
display_header_contact_info:    "true"

resume_header_intro: >-
  <p>Hello, I'm Ömer. I have been involved with software since <b>2016</b>.
  Although the foundation goes back to the 2016 years, I got into graphic design during my university years.
  <b>Influenced by the professors</b> I worked with in academia and my curiosity to work in <b>"niche" areas</b>,
  I have developed myself extensively in <b>typography, packaging design, and corporate identity design.</b>
  With these skills, I started to <b>stand out</b> both in university and in my professional life.
  I have an interest in the unique, I try different paths to be the best, and I strive to create <b>my own race track.</b></p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            ""
  #resume_twitter_url:           ""
  #resume_dribbble_url:          ""
  # resume_facebook_url:         ""
  resume_linkedin_url:          "https://www.linkedin.com/in/omer-ayyildiz-work"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://omerayyildiz.com"
  #resume_medium_url:            "https://medium.com/@omerayyildiz"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
